name: Engine Tests

env:
  paths:
    src/decorators/**
    src/logger.py

on:
  push:
    branches: [ "master" ]
    paths: ${{ env.paths }}
  pull_request:
    branches: [ "master" ]
    paths: ${{ env.paths }}
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  engine-tests:
    uses: ./.github/workflows/testing/testing_workflow_template.yaml
    with:
      use_lfs: false
      test_paths: "tests/decorators tests/logger"
