name: Run Unit Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    env:
      host: "https://staging.picsellia.com/"
      organization_id: "0189266d-64f5-79b4-9b80-6fcf8a3b498b"
      TEST_ORGA: test-account
      api_token: ${{ secrets.API_TOKEN }}
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}


    steps:
      - name : Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Picsellia Package
        run: |
          pip install --upgrade pip
          pip install picsellia
      - name: Run core_utils Unit Tests
        env:
          CORE_UTILS_PATH: "core_utils"
        run: |
          echo "Running tests in $CORE_UTILS_PATH"
          pip install -r "$CORE_UTILS_PATH/requirements.txt"
          python -m unittest discover -s "$CORE_UTILS_PATH" -p 'tests.py'
