name: Run Unit Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name : Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Run Unit Tests in Folders
        run:  |
          # Specify the name of the folder you want to run tests for
          folder_name="yolov8-segmentation-refactored/"
          
          # Check if the folder exists and contains a requirements.txt file
          if [ -d "$folder_name" ] && [ -f "$folder_name/requirements.txt" ]; then
            # Install dependencies from the requirements.txt file
            pip install -r "$folder_name/requirements.txt"
            # Run the unit tests in the tests.py file in the specified folder
            python -m unittest discover -s "$folder_name/experiment" -p 'tests.py'
          else
            echo "Folder or requirements.txt not found in $folder_name"
          fi