name: Run UNet Segmentation Unit Tests
on:
  push:
    branches:
      - 'picsellia-CI-v/**'
    paths:
      - 'unet-instance-segmentation/**'

  pull_request:
    branches:
      - 'feat/ci-workflow'
    paths:
      - 'unet-instance-segmentation/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    env:
      host: "https://staging.picsellia.com/"
      organization_id: "0189266d-64f5-79b4-9b80-6fcf8a3b498b"
      api_token: ${{ secrets.API_TOKEN }}
      SM_FRAMEWORK: "tf.keras"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run UNet Segmentation Unit Tests
        run: |
          pip install -r unet-instance-segmentation/requirements.txt
          python -m unittest -v unet-instance-segmentation/tests.py -k "TestUnetSegmentationUtils"
          python -m unittest -v unet-instance-segmentation/tests.py -k "TestDataset"
          python -m unittest -v unet-instance-segmentation/tests.py -k "TestDataloader"