name: YoloV8 Classification tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/pipelines/yolov8_classification/**'
      - 'src/models/contexts/**'
      - 'src/models/datasets/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/pipelines/yolov8_classification/**'
      - 'src/models/contexts/**'
      - 'src/models/datasets/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  PICSELLIA_TEST_TOKEN: ${{ secrets.PICSELLIA_TEST_TOKEN }}
  PICSELLIA_TEST_HOST: ${{ vars.PICSELLIA_TEST_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install picsellia
        pip install -r requirements-dev.txt
